# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackToTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short description for this forwarding.', max_length=128, verbose_name='Name')),
                ('url', models.CharField(db_index=True, help_text='If you set this to x, you should set slack webhook to https://my_address/slack/x/', max_length=128, verbose_name='Url')),
                ('bot_token', models.CharField(help_text='The token of the bot you want to send telegram messages from.', max_length=128, verbose_name='Bot Token')),
                ('chat_id', models.CharField(help_text='The chat id you want to send the telegram message to. This could be either user id, group id, or channel username (Starting with @)', max_length=128, verbose_name='Chat ID')),
            ],
        ),
    ]
