# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramToSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short description for this forwarding.', max_length=128, verbose_name='Name')),
                ('url', models.CharField(db_index=True, help_text='If you set this to x, you should set telegram webhook to https://my_address/telegram/x/', max_length=128, verbose_name='Url')),
                ('chat_id', models.CharField(help_text='The telegram chat id you want to listen to. This could be either user id, group id, or channel username (Starting with @)', max_length=128, verbose_name='Chat ID')),
                ('slack_hook', models.CharField(help_text='The url of the slack webhook you created', max_length=512, verbose_name='Slack Hook')),
                ('channel', models.CharField(blank=True, help_text='The channel or user you want to send the slack message to. Channels start with # and users start with @.', max_length=128, null=True, verbose_name='Channel')),
            ],
        ),
    ]
